### ISSUE TITLE
AWS 기존 서버 정리 및 신규 서버 Deploy

### ISSUE THREAD

**Issue by trizdreaming** [SADANG-HOBBITS/codename_s#11]
### BACKGROUND

> fedora 무료 서버 사용이 어려워(자료가 거의 없어서) 자료가 많은 ubuntu로 변경
> 서버 자체의 이슈가 중요하지 않기 때문임
### IMPLEMENTATION

> fedora 서버 삭제
> 서버 위치 Tokyo로 변경
> Ubuntu 서버 설치
> 기본 설치 완료 후 이미지 제작까지

**Comment by trizdreaming** [comment]
신규 서버 deploy 완료
조금 고민인게 용량을 30GB 풀로 했는데, image 뜨는데 드는 용량이 유료라면 다시 deploy 해야될수도...

**Comment by blastingzone** [comment]
ㅋ ㅑ

**Comment by trizdreaming** [comment]
AMI 이미지를 따면 connection이 작살나는 경우가 있네요.
서버 기본 세팅으로는 utf8 적용된 mysql 서버 구동입니다.
